# -*- coding: utf-8 -*-
"""生成 08-优化算法/教学/01、02 两篇 notebook（nbformat 4）。"""
import json, io, sys, os
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

OUT = '08-优化算法/教学'
os.makedirs(OUT, exist_ok=True)
os.makedirs(os.path.join(OUT, 'images'), exist_ok=True)

META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10.0"},
}

def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}

def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": list(lines)}

# =====================================================================
# 01-梯度下降与迭代优化入门
# =====================================================================
nb01 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# ⚙️ 01-梯度下降与迭代优化入门\n",
   "\n",
   "> 目标：从**沿负梯度下降**这个最小动作出发，建立「步长（学习率）→ 收敛性 → 噪声」的直觉，并为后续\n",
   "> 动量 / 自适应 / 二阶方法搭好对照系。\n",
   "\n",
   "## §1 为什么从梯度下降讲起\n",
   "\n",
   "所有优化器（SGD / Momentum / AdaGrad / Adam / 牛顿法）都共享同一个骨架：\n",
   "\n",
   "$$w_{t+1} = w_t - \\eta \\, \\text{（某种更新方向）}$$\n",
   "\n",
   "区别只在**更新方向怎么构造**：\n",
   "\n",
   "| 家族 | 更新方向 | 解决什么 | 代价 |\n",
   "|------|----------|----------|------|\n",
   "| SGD | $-g$ | 最基本 | 病态曲率震荡 / 无历史 / 一刀切 lr |\n",
   "| 动量族 | 历史梯度 EMA $v$ | 震荡、平坦区 | 多一份状态 $v$ |\n",
   "| 自适应 | $g/\\sqrt{E[g^2]}$ | 逐参数步长（稀疏） | 多一份状态、泛化争议 |\n",
   "| 二阶 | $H^{-1}g$ | 曲率自适应（牛顿） | $H$ 是 $n^2$ 存不下 |\n",
   "\n",
   "**本节先只讲 SGD**：学习率怎么选、为什么过大发散、mini-batch 噪声从哪来。"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 手写梯度下降（统一接口：step(w, g, t) -> w） ----------\n",
"def sgd_step(w, g, t, lr=0.1):\n",
"    return w - lr * g\n",
"\n",
"def run_gd(f, grad_f, w0, steps, step_fn):\n",
"    w = w0.copy()\n",
"    hist = [w.copy()]\n",
"    for t in range(steps):\n",
"        g = grad_f(w)\n",
"        w = step_fn(w, g, t)\n",
"        hist.append(w.copy())\n",
"    return np.array(hist)"),
code(
"# ---------- 实验 1：一维凸函数 f(x)=x^2，最优步长可解析 ----------\n",
"# 解析最优步长：f(x)=0.5*a*x^2 -> 梯度=a*x -> 最优 eta=1/a（一步到位）\n",
"a = 2.0\n",
"f = lambda x: 0.5 * a * x**2\n",
"gf = lambda x: a * x\n",
"\n",
"fig, axes = plt.subplots(1, 3, figsize=(12, 3.4))\n",
"cases = [('eta=0.5 (一步到位)', 0.5, 5, '#55A868'),\n",
"         ('eta=1.1 (发散)', 1.1, 6, '#C44E52'),\n",
"         ('eta=0.05 (过小)', 0.05, 30, '#4C72B0')]\n",
"xs = np.linspace(-2.5, 2.5, 400)\n",
"for ax, (ttl, eta, steps, col) in zip(axes, cases):\n",
"    ax.plot(xs, f(xs), color='#8E8E93', lw=1.5, label='f(x)')\n",
"    hist = run_gd(f, gf, np.array([2.0]), steps, lambda w, g, t: w - eta * g)\n",
"    ax.plot(hist[:, 0], f(hist[:, 0]), 'o-', color=col, lw=1.2, ms=4, label='GD 轨迹')\n",
"    ax.axhline(0, color='k', lw=0.6)\n",
"    ax.set_title(ttl, fontsize=11)\n",
"    ax.set_xlim(-2.6, 2.6); ax.set_ylim(-0.4, 7)\n",
"    ax.legend(fontsize=8, loc='upper center')\n",
"    ax.grid(alpha=0.3)\n",
"fig.suptitle('学习率三态：一步到位 / 发散 / 蜗牛爬', fontsize=12)\n",
"plt.tight_layout(); plt.show()\n",
"print('结论：eta > 1/a 时 |w| 逐次放大 -> 发散；eta 过小则收敛极慢')"),
code(
"# ---------- 实验 2：BGD / SGD / Mini-batch 的噪声来源 ----------\n",
"rng = np.random.default_rng(42)\n",
"N, D = 200, 2\n",
"X = rng.normal(size=(N, D)); X[:, 0] = 1.0  # 带偏置\n",
"w_true = np.array([0.5, -1.2])\n",
"y = X @ w_true + rng.normal(scale=0.3, size=N)\n",
"\n",
"def loss_grad(w, idx):  # 在 idx 子集上算平均梯度\n",
"    r = X[idx] @ w - y[idx]\n",
"    return X[idx].T @ r / len(idx)\n",
"\n",
"def train(mode, epochs=60, batch=16, lr=0.2):\n",
"    w = np.zeros(D); hist = [w.copy()]\n",
"    for e in range(epochs):\n",
"        if mode == 'BGD':\n",
"            g = loss_grad(w, np.arange(N))\n",
"        elif mode == 'SGD':\n",
"            g = loss_grad(w, np.array([rng.integers(N)]))\n",
"        else:\n",
"            idx = rng.integers(N, size=batch)\n",
"            g = loss_grad(w, idx)\n",
"        w = w - lr * g\n",
"        hist.append(w.copy())\n",
"    return np.array(hist)\n",
"\n",
"fig, ax = plt.subplots(figsize=(7.5, 4.2))\n",
"for mode, col in [('BGD', '#4C72B0'), ('Mini-batch', '#55A868'), ('SGD', '#C44E52')]:\n",
"    hist = train(mode)\n",
"    dist = np.linalg.norm(hist - w_true, axis=1)\n",
"    ax.plot(dist, label=f'{mode}（每步 1 次小梯度）', color=col, lw=1.4)\n",
"ax.set_xlabel('epoch'); ax.set_ylabel('||w - w*||')\n",
"ax.set_title('三种梯度估计的收敛轨迹（同数据同初始，仅梯度估计方式不同）', fontsize=11)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()\n",
"print('BGD 平滑单调；Mini-batch 有小噪声但快；SGD（单样本）噪声最大')"),
md("## §2 公式与直觉（背诵）\n",
   "\n",
   "- **更新**：$w \\gets w - \\eta g$，$g = \\nabla_w \\mathcal{L}$\n",
   "- **一阶必要条件**：局部极小处 $\\nabla f = 0$（凸函数时即全局）\n",
   "- **凸函数**：$f(\\theta x + (1-\\theta)y) \\le \\theta f(x) + (1-\\theta)f(y)$ → 梯度下降保证收敛\n",
   "- **收敛速度**（强凸）：$f(w_t)-f^* \\le O((1-\\kappa^{-1})^t)$，条件数 $\\kappa=\\lambda_{max}/\\lambda_{min}$ 越大越慢\n",
   "- **为什么 mini-batch**：期望等于全梯度（无偏估计），方差随 batch 反比下降，单样本噪声大但算得快\n",
   "\n",
   "## §3 常见 bug 与边界\n",
   "\n",
   "- **lr 与特征尺度不匹配**：特征未归一化时，不同维度的梯度差几个数量级，一个 lr 顾此失彼 → 先标准化\n",
   "- **lr 过大立即 NaN**：检查第一步 loss 是否为 inf\n",
   "- **忘记梯度清零**：手写时每次迭代 `g = grad(w)` 而不是 `g += grad(w)`\n",
   "- **停止条件**：`||g|| < tol` 或 loss 相对下降 < tol，不要只看绝对 loss\n",
   "\n",
   "## §4 面试追问与扩展\n",
   "\n",
   "1. **学习率怎么选**：先 0.01/0.001/0.1 三档粗扫，再观察 loss 曲线（震荡→降 lr；太缓→升）\n",
   "2. **凸 vs 非凸**：神经网络非凸，收敛保证不适用；但局部极小通常足够好（高维时鞍点比局部极小更常见）\n",
   "3. **为什么有时 loss 曲线毛刺**：mini-batch 噪声 → 用指数滑动平均平滑后观察趋势\n",
   "4. **梯度下降与牛顿法关系**：牛顿法 = 梯度下降在「以 H 为度量的内积空间」里的最速下降（见 06 篇）\n",
   "\n",
   "## §5 自测清单\n",
   "\n",
   "- [ ] 手写 SGD 并在 $f=0.5x^2$ 上验证「$\\eta=1/a$ 一步到位」\n",
   "- [ ] 解释 lr 过大的发散机制（$|w_{t+1}| = |1-\\eta a||w_t| > |w_t|$）\n",
   "- [ ] 说明 BGD / SGD / Mini-batch 的噪声-速度权衡\n",
   "- [ ] 默写强凸收敛速率 $O((1-\\kappa^{-1})^t)$ 并说明条件数含义\n",
   "- [ ] 能回答「loss 曲线震荡怎么办」\n",
   "\n",
   "> 💡 下节预告：峡谷地形 + 历史动量（02 篇），自适应步长（03 篇）。"),
]
}

# =====================================================================
# 02-动量族与加速方法
# =====================================================================
nb02 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 🏃 02-动量族与加速方法\n",
   "\n",
   "> 目标：理解**动量 = 对历史梯度做指数滑动平均（EMA）**，为什么能压震荡、穿峡谷、过鞍点；\n",
   "> 以及 Nesterov（NAG）「先看未来再迈步」的差别。\n",
   "\n",
   "## §1 病态曲率：峡谷地形的困境\n",
   "\n",
   "设 $f(w) = w_1^2 + 40\\,w_2^2$：$w_2$ 方向梯度大 40 倍（陡壁），$w_1$ 方向平坦（峡谷底）。\n",
   "SGD 在陡壁上大步来回震荡、沿谷底前进缓慢。\n",
   "\n",
   "**动量直觉**：把每次梯度的方向做 EMA，陡壁上的正负梯度相互抵消，谷底方向被累积 → 前进更稳更快。\n",
   "\n",
   "$$v_t = \\beta v_{t-1} + g_t, \\qquad w_t = w_{t-1} - \\eta v_t, \\qquad \\beta = 0.9$$\n",
   "\n",
   "> $v$ 是「速度」，$\\beta$ 是摩擦系数（保留多少旧速度）。"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"def sgd(w, g, t, lr=0.01):\n",
"    return w - lr * g, None\n",
"\n",
"def momentum(w, g, t, lr=0.01, beta=0.9, v=None):\n",
"    v = beta * v + g if v is not None else g\n",
"    return w - lr * v, v\n",
"\n",
"def nesterov(w, g, t, lr=0.01, beta=0.9, v=None):\n",
"    # 前瞻：先用当前速度冲一步，在那里的梯度作为真实梯度\n",
"    v_prev = beta * v if v is not None else 0.0\n",
"    lookahead = w - lr * beta * v_prev\n",
"    # 简化实现：直接用峡谷梯度函数在 lookahead 处重算\n",
"    g_ahead = canyon_grad(lookahead)\n",
"    v = beta * v + g_ahead if v is not None else g_ahead\n",
"    return w - lr * v, v\n",
"\n",
"def canyon_grad(w):\n",
"    return np.array([2.0 * w[0], 80.0 * w[1]])  # 峡谷：y 方向陡 40 倍"),
code(
"# ---------- 实验 1：峡谷地形收敛轨迹对比 ----------\n",
"w0 = np.array([1.0, 0.7])\n",
"\n",
"def run(opt, steps=120, lr=0.02, beta=0.9):\n",
"    w = w0.copy(); v = None; pts = [w.copy()]\n",
"    for t in range(steps):\n",
"        g = canyon_grad(w)\n",
"        if opt == 'sgd':\n",
"            w, v = sgd(w, g, t, lr)\n",
"        elif opt == 'mom':\n",
"            w, v = momentum(w, g, t, lr, beta, v)\n",
"        else:\n",
"            w, v = nesterov(w, g, t, lr, beta, v)\n",
"        pts.append(w.copy())\n",
"    return np.array(pts)\n",
"\n",
"fig, axes = plt.subplots(1, 3, figsize=(12.5, 4))\n",
"w1 = np.linspace(-1.2, 1.2, 200); w2 = np.linspace(-1.0, 1.0, 200)\n",
"W1, W2 = np.meshgrid(w1, w2)\n",
"Z = W1**2 + 40 * W2**2\n",
"for ax, (name, col) in zip(axes, [('SGD', '#C44E52'), ('Momentum', '#4C72B0'), ('NAG', '#55A868')]):\n",
"    ax.contour(W1, W2, Z, levels=12, cmap='Greys', alpha=0.5)\n",
"    pts = run(name)\n",
"    ax.plot(pts[:, 0], pts[:, 1], '.-', color=col, lw=1.2, ms=3)\n",
"    ax.plot(w0[0], w0[1], 'ks', ms=6)\n",
"    ax.set_title(f'{name}（120 步）', fontsize=11)\n",
"    ax.set_xlim(-1.25, 1.25); ax.set_ylim(-1.05, 1.05)\n",
"    ax.set_aspect('equal'); ax.grid(alpha=0.25)\n",
"fig.suptitle('峡谷地形：SGD 沿壁震荡 vs 动量平滑前进 vs NAG 更贴谷底', fontsize=12)\n",
"plt.tight_layout(); plt.show()\n",
"\n",
"for name in ['sgd', 'mom', 'nesterov']:\n",
"    pts = run(name)\n",
"    print(f'{name:9s} 终点 |w| = {np.linalg.norm(pts[-1]):.4f}')"),
md("## §2 公式总表（背诵）\n",
   "\n",
   "| 方法 | 速度更新 | 参数更新 |\n",
   "|------|----------|----------|\n",
   "| SGD | — | $w \\gets w - \\eta g$ |\n",
   "| Momentum | $v \\gets \\beta v + g$ | $w \\gets w - \\eta v$ |\n",
   "| Nesterov | $v \\gets \\beta v + \\nabla f(w - \\eta\\beta v)$ | $w \\gets w - \\eta v$ |\n",
   "\n",
   "- 展开 EMA：$v_t = \\sum_{i=0}^{t} \\beta^{t-i} g_i$ → 越近的梯度权重越大（衰减系数 $\\beta^{\\Delta}$）\n",
   "- **有效时间窗**：$\\beta=0.9$ 时约 10 步，$\\beta=0.99$ 时约 100 步\n",
   "- **与 lr 的关系**：动量让有效步长变大，通常 lr 需比 SGD 小一些\n",
   "\n",
   "## §3 常见 bug 与边界\n",
   "\n",
   "- **首步 `v=None` 判断**：`beta * None` 会崩 → 首步直接用 $g$\n",
   "- **状态按参数独立**：每个权重张量一份 $v$，全局共享会串\n",
   "- **NAG 实现**：先更新到前瞻点算梯度，再回推；工程上 PyTorch 用「当前点更新 + 下次提前修正」的等价写法\n",
   "- **β 过大**（0.99+）会overshoot，loss 反弹\n",
   "\n",
   "## §4 面试追问与扩展\n",
   "\n",
   "1. **为什么动量能过鞍点**：鞍点处 $g \\approx 0$，SGD 停住；动量带着历史速度直接冲过去\n",
   "2. **Momentum vs NAG**：NAG 在前瞻点（$w-\\eta\\beta v$）处算梯度，对「即将下坡」更敏感，收敛更稳（凸问题上加速）\n",
   "3. **与 Adam 的关系**：Adam 的一阶矩就是动量（EMA of $g$），但步长再除以二阶矩\n",
   "4. **CV 上 SGD+Momentum 为何常胜 Adam**：见 03 篇（平坦极小值假说）\n",
   "\n",
   "## §5 自测清单\n",
   "\n",
   "- [ ] 默写 Momentum / NAG 两条公式并说明 $\\beta$ 含义\n",
   "- [ ] 手写峡谷实验，对比三种轨迹（本文已出图）\n",
   "- [ ] 解释「动量抵消陡壁震荡、累积谷底方向」\n",
   "- [ ] 解释为什么动量能穿鞍点\n",
   "- [ ] 说清 NAG 的梯度在哪里算\n",
   "\n",
   "> 💡 下节预告：AdaGrad / RMSProp / Adam 的自适应步长（03 篇）。"),
]
}

for fn, nb in [('01-梯度下降与迭代优化入门.ipynb', nb01),
               ('02-动量族与加速方法.ipynb', nb02)]:
    with open(os.path.join(OUT, fn), 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print('created', fn)
