# -*- coding: utf-8 -*-
"""生成 08-优化算法/教学/03、04 两篇 notebook（含 torch 对照）。"""
import json, io, sys, os
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

OUT = '08-优化算法/教学'
os.makedirs(OUT, exist_ok=True)
os.makedirs(os.path.join(OUT, 'images'), exist_ok=True)

META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10.0"},
}

def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}

def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": list(lines)}

# =====================================================================
# 03-自适应学习率与Adam
# =====================================================================
nb03 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 🎛️ 03-自适应学习率与 Adam\n",
   "\n",
   "> 目标：回答三个问题——**为什么逐参数步长**（稀疏特征）、**AdaGrad 为什么后期停摆**、\n",
   "> **Adam 的偏差校正在干什么**。并手写 Adam 与 `torch.optim.Adam` 逐位对照。\n",
   "\n",
   "## §1 一刀切学习率的问题\n",
   "\n",
   "词向量等**稀疏特征**：少数样本才出现，梯度稀有但需要大更新；密集特征需要稳定小步长。\n",
   "统一 $\\eta$ 无法两全 → 思路：**每个参数按自身历史梯度幅度缩放步长**。\n",
   "\n",
   "## §2 三步演化（背诵主线）\n",
   "\n",
   "| 优化器 | 统计量 | 更新 | 问题 |\n",
   "|--------|--------|------|------|\n",
   "| AdaGrad | $G \\gets G + g^2$（累加） | $w \\gets w - \\frac{\\eta}{\\sqrt{G}+\\epsilon}g$ | $G$ 单调增 → 步长 $\\to 0$，后期停摆 |\n",
   "| RMSProp | $E \\gets \\beta E + (1-\\beta)g^2$（EMA） | $w \\gets w - \\frac{\\eta}{\\sqrt{E}+\\epsilon}g$ | 无动量，仍用固定 $\\eta$ |\n",
   "| Adam | $m,v$ 双 EMA + 偏差校正 | $w \\gets w - \\eta \\frac{\\hat m}{\\sqrt{\\hat v}+\\epsilon}$ | 参数量 ×2 状态 |\n",
   "\n",
   "**Adam 四条公式**（Kingma & Ba 2015）：\n",
   "\n",
   "$$m_t = \\beta_1 m_{t-1} + (1-\\beta_1)g_t \\qquad v_t = \\beta_2 v_{t-1} + (1-\\beta_2)g_t^2$$\n",
   "$$\\hat m_t = \\frac{m_t}{1-\\beta_1^t} \\qquad \\hat v_t = \\frac{v_t}{1-\\beta_2^t} \\qquad w \\gets w - \\eta \\frac{\\hat m_t}{\\sqrt{\\hat v_t}+\\epsilon}$$\n",
   "\n",
   "> **为什么校正**：$m_1 = (1-\\beta_1)g_1$，被 $1-\\beta_1=0.1$ 缩小了 10 倍；除以 $1-\\beta_1^t$ 恰好还原「真实 EMA 权重和」。（EMA 权重和为 $\\sum_{i=0}^{t-1}\\beta^i = (1-\\beta^t)/(1-\\beta)$，除以它即归一化。）"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 手写三类自适应优化器（统一接口 step(w, g, t)） ----------\n",
"class AdaGrad:\n",
"    def __init__(self, lr=0.1, eps=1e-8):\n",
"        self.lr, self.eps = lr, eps\n",
"        self.G = None\n",
"    def step(self, w, g, t):\n",
"        self.G = g * g if self.G is None else self.G + g * g\n",
"        return w - self.lr * g / (np.sqrt(self.G) + self.eps)\n",
"\n",
"class RMSProp:\n",
"    def __init__(self, lr=0.01, beta=0.9, eps=1e-8):\n",
"        self.lr, self.beta, self.eps = lr, beta, eps\n",
"        self.E = None\n",
"    def step(self, w, g, t):\n",
"        self.E = (1 - self.beta) * g * g if self.E is None else self.beta * self.E + (1 - self.beta) * g * g\n",
"        return w - self.lr * g / (np.sqrt(self.E) + self.eps)\n",
"\n",
"class Adam:\n",
"    def __init__(self, lr=0.01, b1=0.9, b2=0.999, eps=1e-8):\n",
"        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps\n",
"        self.m = self.v = None\n",
"    def step(self, w, g, t):\n",
"        t1 = t + 1\n",
"        self.m = (1 - self.b1) * g if self.m is None else self.b1 * self.m + (1 - self.b1) * g\n",
"        self.v = (1 - self.b2) * g * g if self.v is None else self.b2 * self.v + (1 - self.b2) * g * g\n",
"        m_hat = self.m / (1 - self.b1**t1)\n",
"        v_hat = self.v / (1 - self.b2**t1)\n",
"        return w - self.lr * m_hat / (np.sqrt(v_hat) + self.eps)"),
code(
"# ---------- 实验 1：稀疏特征场景（10 维，只有 0 号特征常出现） ----------\n",
"rng = np.random.default_rng(0)\n",
"N, D = 500, 10\n",
"X = np.zeros((N, D))\n",
"for i in range(N):\n",
"    X[i, rng.integers(0, D)] = 1.0          # 每个样本只有一个特征=1（稀疏）\n",
"    if i % 10 == 0:\n",
"        X[i, 0] = 1.0                        # 0 号特征频繁出现\n",
"w_true = rng.normal(size=D)\n",
"y = X @ w_true + rng.normal(scale=0.1, size=N)\n",
"\n",
"def train(opt_factory, epochs=40, lr=None):\n",
"    w = np.zeros(D); dists = [np.linalg.norm(w - w_true)]\n",
"    for e in range(epochs):\n",
"        g = X.T @ (X @ w - y) / N\n",
"        w = opt_factory(lr=lr).step(w, g, e) if lr else opt_factory().step(w, g, e)\n",
"        dists.append(np.linalg.norm(w - w_true))\n",
"    return np.array(dists)\n",
"\n",
"fig, ax = plt.subplots(figsize=(7.5, 4.2))\n",
"ax.plot(train(lambda lr=None: type('S', (), {'step': lambda s, w, g, t: w - 0.2 * g})(), 40),\n",
"       label='SGD lr=0.2', color='#C44E52', lw=1.4)\n",
"ax.plot(train(lambda lr=0.5: AdaGrad(lr=lr), 40), label='AdaGrad lr=0.5', color='#DD8452', lw=1.4)\n",
"ax.plot(train(lambda lr=0.5: RMSProp(lr=lr), 40), label='RMSProp lr=0.5', color='#55A868', lw=1.4)\n",
"ax.plot(train(lambda lr=0.5: Adam(lr=lr), 40), label='Adam lr=0.5', color='#4C72B0', lw=1.4)\n",
"ax.set_xlabel('epoch'); ax.set_ylabel('||w - w*||')\n",
"ax.set_title('稀疏线性回归：自适应步长 vs SGD（自适应族更快逼近真值）', fontsize=11)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()"),
code(
"# ---------- 实验 2：AdaGrad 后期停摆演示 ----------\n",
"# 固定一个小梯度 g=0.01，看步长如何随时间衰减\n",
"steps = 500\n",
"G = 0.0; lr = 1.0; eps = 1e-8\n",
"steps_adagrad = []\n",
"for t in range(steps):\n",
"    G += 0.01**2\n",
"    steps_adagrad.append(lr / (np.sqrt(G) + eps))\n",
"E = 0.0; beta = 0.9\n",
"steps_rms = []\n",
"for t in range(steps):\n",
"    E = beta * E + (1 - beta) * 0.01**2\n",
"    steps_rms.append(lr / (np.sqrt(E) + eps))\n",
"\n",
"fig, ax = plt.subplots(figsize=(7.5, 3.8))\n",
"ax.plot(steps_adagrad, label='AdaGrad 步长', color='#DD8452', lw=1.5)\n",
"ax.plot(steps_rms, label='RMSProp 步长', color='#55A868', lw=1.5)\n",
"ax.set_xlabel('step'); ax.set_ylabel('有效步长 lr/(sqrt(G)+eps)')\n",
"ax.set_title('恒定小梯度下：AdaGrad 步长趋 0，RMSProp 稳定', fontsize=11)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()"),
code(
"# ---------- 实验 3：手写 Adam vs torch.optim.Adam 逐位对照 ----------\n",
"import torch\n",
"\n",
"torch.manual_seed(1)\n",
"w_torch = torch.randn(5, 3, dtype=torch.float64, requires_grad=True)\n",
"w_np = w_torch.detach().numpy().copy()\n",
"\n",
"opt_t = torch.optim.Adam([w_torch], lr=0.01, betas=(0.9, 0.999), eps=1e-8)\n",
"adam = Adam(lr=0.01, b1=0.9, b2=0.999, eps=1e-8)\n",
"\n",
"maxdiff = 0.0\n",
"for t in range(20):\n",
"    # 相同的随机梯度\n",
"    g = torch.randn(5, 3, dtype=torch.float64)\n",
"    loss = (w_torch * g).sum()\n",
"    opt_t.zero_grad(); loss.backward()\n",
"    opt_t.step()\n",
"    # 手写版用同样梯度\n",
"    w_np = adam.step(w_np, g.numpy(), t)\n",
"    diff = np.abs(w_np - w_torch.detach().numpy()).max()\n",
"    maxdiff = max(maxdiff, diff)\n",
"print(f'手写 Adam vs torch.optim.Adam 最大误差: {maxdiff:.2e}')\n",
"assert maxdiff < 1e-12, '对照失败'\n",
"print('对照通过：完全一致')"),
md("## §3 超参与工程建议（必背）\n",
   "\n",
   "| 优化器 | 默认 lr | 关键超参 | 适用 |\n",
   "|--------|--------|----------|------|\n",
   "| AdaGrad | 0.01 | — | 稀疏特征（词向量） |\n",
   "| RMSProp | 0.001 | $\\beta=0.9$ | RNN（Hinton 原版） |\n",
   "| Adam | 0.001 | $\\beta_1=0.9,\\ \\beta_2=0.999$ | 默认首选（NLP/RL/生成） |\n",
   "\n",
   "- **ε 的位置**：$1/(\\sqrt{v}+\\epsilon)$，不是 $1/\\sqrt{v+\\epsilon}$（数值性质不同）\n",
   "- **Adam 与权重衰减耦合**：L2 正则被自适应步长干扰 → AdamW（04 篇）\n",
   "- **CV 上 Adam 常输给 SGD+Momentum**：平坦极小值假说（Adam 收敛到尖锐极小，泛化差）\n",
   "\n",
   "## §4 常见 bug 与边界\n",
   "\n",
   "- **偏差校正遗漏**：忘除以 $1-\\beta^t$，头几百步更新量异常小\n",
   "- **状态共享**：m/v 必须按参数张量独立维护\n",
   "- **首步 None**：`m=None` 时直接取 $g$（等价于 EMA 从 0 开始）\n",
   "- **lr 忘调度**：Adam 不调度一般也能用，但配上 warmup+decay 更好（05 篇）\n",
   "\n",
   "## §5 面试追问与扩展\n",
   "\n",
   "1. **Adam vs SGD 最终精度**：Adam 快、稳；SGD+Momentum+调度在部分 CV 任务泛化更好\n",
   "2. **为什么 RNN 用 RMSProp/Adam**：RNN 梯度跨步尺度剧变，逐元素缩放能稳住\n",
   "3. **偏差校正的另一种等价解释**：把 EMA 归一化（除以权重和）\n",
   "4. **Adam 在 LLM 中的表现**：锁死 AdamW + 特殊调度（见 04/05/07 篇）\n",
   "\n",
   "## §6 自测清单\n",
   "\n",
   "- [ ] 默写 AdaGrad / RMSProp / Adam 公式\n",
   "- [ ] 默写 Adam 偏差校正并解释为什么\n",
   "- [ ] 手写 Adam 与 torch 对照（本文已断言）\n",
   "- [ ] 解释 AdaGrad 后期停摆、RMSProp 如何修复\n",
   "- [ ] 说清默认超参（lr/β₁/β₂/ε）\n",
   "\n",
   "> 💡 下节预告：AdamW 解耦权重衰减与 LAMB / Lion（04 篇）。"),
]
}

# =====================================================================
# 04-Adam变体与解耦权重衰减
# =====================================================================
nb04 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 🧊 04-Adam 变体与解耦权重衰减\n",
   "\n",
   "> 目标：把「权重衰减」和「L2 正则」掰开——**为什么 Adam 里它们不一样**（AdamW 解耦），\n",
   "> 以及大模型训练锁死 AdamW 的原因；顺带过 NAdam / AMSGrad / LAMB / Lion。\n",
   "\n",
   "## §1 L2 正则与 Adam 的耦合问题\n",
   "\n",
   "朴素做法（Adam+L2）：$g \\gets g + \\lambda w$，再进 Adam。\n",
   "\n",
   "问题：权重大 → 梯度项大 → $\\sqrt{\\hat v}$ 大 → **L2 贡献被自适应步长缩小**。\n",
   "即**正则化强度被参数幅度反向调制**，大权重几乎不衰减——与「权重衰减应一视同仁」的初衷矛盾。\n",
   "\n",
   "**AdamW（Loshchilov & Hutter 2019）**：把衰减从梯度里拿出来，直接乘到参数上：\n",
   "\n",
   "$$\\boxed{\\;w \\gets w - \\eta\\,\\hat m_t/(\\sqrt{\\hat v_t}+\\epsilon) - \\eta\\lambda w\\; }$$\n",
   "\n",
   "> 第二项与梯度无关：无论自适应步长如何，权重都按固定比例 $\\eta\\lambda$ 衰减。"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 手写 Adam（可切换 L2 / 解耦衰减） ----------\n",
"class AdamWithDecay:\n",
"    def __init__(self, lr=0.01, b1=0.9, b2=0.999, eps=1e-8, wd=0.0, decoupled=False):\n",
"        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps\n",
"        self.wd, self.decoupled = wd, decoupled\n",
"        self.m = self.v = None\n",
"    def step(self, w, g, t):\n",
"        t1 = t + 1\n",
"        g_eff = g + self.wd * w if not self.decoupled else g   # L2：进梯度；解耦：不进\n",
"        self.m = (1 - self.b1) * g_eff if self.m is None else self.b1 * self.m + (1 - self.b1) * g_eff\n",
"        self.v = (1 - self.b2) * g_eff * g_eff if self.v is None else self.b2 * self.v + (1 - self.b2) * g_eff * g_eff\n",
"        m_hat = self.m / (1 - self.b1**t1)\n",
"        v_hat = self.v / (1 - self.b2**t1)\n",
"        w_new = w - self.lr * m_hat / (np.sqrt(v_hat) + self.eps)\n",
"        if self.decoupled:\n",
"            w_new = w_new - self.lr * self.wd * w\n",
"        return w_new"),
code(
"# ---------- 实验 1：手写 AdamW vs torch.optim.AdamW 逐位对照 ----------\n",
"import torch\n",
"\n",
"torch.manual_seed(7)\n",
"w_t = torch.randn(4, 4, dtype=torch.float64, requires_grad=True)\n",
"w_n = w_t.detach().numpy().copy()\n",
"\n",
"opt_t = torch.optim.AdamW([w_t], lr=0.01, betas=(0.9, 0.999), eps=1e-8, weight_decay=0.01)\n",
"mine = AdamWithDecay(lr=0.01, b1=0.9, b2=0.999, eps=1e-8, wd=0.01, decoupled=True)\n",
"\n",
"maxdiff = 0.0\n",
"for t in range(15):\n",
"    g = torch.randn(4, 4, dtype=torch.float64)\n",
"    (w_t * g).sum().backward()\n",
"    opt_t.step(); opt_t.zero_grad()\n",
"    w_n = mine.step(w_n, g.numpy(), t)\n",
"    maxdiff = max(maxdiff, np.abs(w_n - w_t.detach().numpy()).max())\n",
"print(f'手写 AdamW vs torch.optim.AdamW 最大误差: {maxdiff:.2e}')\n",
"assert maxdiff < 1e-12\n",
"print('对照通过')"),
code(
"# ---------- 实验 2：解耦 vs 耦合衰减对大权重的影响 ----------\n",
"rng = np.random.default_rng(0)\n",
"w = rng.normal(scale=3.0, size=200)   # 大初始权重\n",
"g = np.zeros_like(w)                  # 无梯度（看纯衰减行为）\n",
"\n",
"def pure_decay(decoupled, steps=200, lr=0.1, wd=0.05):\n",
"    o = AdamWithDecay(lr=lr, wd=wd, decoupled=decoupled)\n",
"    ww = w.copy(); norms = []\n",
"    for t in range(steps):\n",
"        ww = o.step(ww, g, t)\n",
"        norms.append(np.linalg.norm(ww))\n",
"    return np.array(norms)\n",
"\n",
"fig, ax = plt.subplots(figsize=(7.5, 4.0))\n",
"ax.plot(pure_decay(True),  label='AdamW 解耦衰减', color='#4C72B0', lw=1.6)\n",
"ax.plot(pure_decay(False), label='Adam+L2（进梯度）', color='#C44E52', lw=1.6)\n",
"ax.set_xlabel('step'); ax.set_ylabel('||w||')\n",
"ax.set_title('零梯度下纯衰减行为：解耦版匀速衰减，耦合版被统计量压制', fontsize=11)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()\n",
"print('解耦衰减按固定比例缩；耦合衰减首步 v=0 时几乎不动')"),
md("## §2 变体总表（面试背诵）\n",
   "\n",
   "| 变体 | 改动 | 解决什么 |\n",
   "|------|------|----------|\n",
   "| **AdamW** | 权重衰减解耦：`w -= lr*wd*w` | L2 与自适应步长耦合 → **LLM 默认** |\n",
   "| NAdam | 一阶矩带 Nesterov 前瞻 | Adam 收敛再快一点 |\n",
   "| AMSGrad | $\\hat v = \\max(\\hat v_{t-1}, \\hat v_t)$（单调不减） | 防 Adam 在非凸问题上步长反复增大 |\n",
   "| **LAMB** | 逐层步长归一：`lr * ||w|| / ||m_hat/(sqrt(v_hat)+eps)||` | 大 batch（数千）训练不炸 |\n",
   "| **Lion** | `w -= lr * sign(b1*m + (1-b1)*g)` | 省显存省算力，只用符号 |\n",
   "| Adafactor | 二阶矩按行/列分解近似 | 省内存（T5 用） |\n",
   "\n",
   "## §3 为什么大模型锁死 AdamW\n",
   "\n",
   "- 权重衰减解耦 → 正则强度不受幅度调制，训练更稳\n",
   "- 配合 warmup + cosine + 梯度裁剪（05 篇）成为 LLM 训练标配（GPT / LLaMA 系）\n",
   "- AdamW 在 Transformer 上普遍优于 Adam+L2（正则化与自适应解耦）\n",
   "\n",
   "## §4 常见 bug 与边界\n",
   "\n",
   "- **PyTorch 默认**：`optim.AdamW` 的 `weight_decay` 默认走解耦路径，不要和 L2 混写\n",
   "- **decoupled 衰减不放梯度里**：放梯度里就不是 AdamW 了\n",
   "- **Lion 无二阶矩**：不存 $v$，省一半优化器内存；但超参（lr 通常更小）要重新调\n",
   "\n",
   "## §5 面试追问与扩展\n",
   "\n",
   "1. **LAMB 为什么能大 batch**：每层梯度范数差异大，按参数范数归一化步长，避免某层被压死\n",
   "2. **Adafactor 省多少**：二阶矩从 $O(n)$ 降为 $O(\\sqrt n)$（行+列因子）\n",
   "3. **AdamW vs SGD+wd**：对小模型差异小，对 Transformer 明显\n",
   "\n",
   "## §6 自测清单\n",
   "\n",
   "- [ ] 默写 AdamW 更新公式（衰减项写在参数更新里）\n",
   "- [ ] 解释「L2 与自适应步长耦合」的机制\n",
   "- [ ] 手写 AdamW 与 torch 对照（本文已断言）\n",
   "- [ ] 一句话说清 LAMB / Lion / AMSGrad 各改了什么\n",
   "- [ ] 为什么 LLM 训练默认 AdamW\n",
   "\n",
   "> 💡 下节预告：学习率调度（warmup/cosine）与梯度裁剪/累积（05 篇）。"),
]
}

for fn, nb in [('03-自适应学习率与Adam.ipynb', nb03),
               ('04-Adam变体与解耦权重衰减.ipynb', nb04)]:
    with open(os.path.join(OUT, fn), 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print('created', fn)
