# -*- coding: utf-8 -*-
"""生成 08-优化算法/教学/05、06、07 三篇 notebook。"""
import json, io, sys, os
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

OUT = '08-优化算法/教学'
os.makedirs(OUT, exist_ok=True)
os.makedirs(os.path.join(OUT, 'images'), exist_ok=True)

META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10.0"},
}

def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}

def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": list(lines)}

# =====================================================================
# 05-学习率调度与训练策略
# =====================================================================
nb05 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 📉 05-学习率调度与训练策略\n",
   "\n",
   "> 目标：warmup / cosine / step 调度的**为什么**，以及梯度裁剪、梯度累积、EMA 三个训练技巧的数学原理。\n",
   "\n",
   "## §1 为什么需要调度\n",
   "\n",
   "- **前期（warmup）**：训练初期梯度方差大、方向不可信，直接大步长会破坏预训练分布 / 让 loss 炸 → 从小步长线性升到峰值\n",
   "- **后期（decay）**：接近极小值时步长应缩小才能精细收敛（振荡减小）\n",
   "- **常用组合**：`linear warmup -> cosine decay`（LLM 标配）、`step decay`（每隔 N 轮 ×0.1）、`exp decay`、`plateau`（loss 停降再减）\n",
   "\n",
   "$$\\text{warmup: } \\eta_t = \\eta_{max}\\frac{t}{T_w}\\ (t<T_w)\\qquad\\text{cosine: } \\eta_t = \\eta_{min} + \\frac{\\eta_{max}-\\eta_{min}}{2}\\left(1+\\cos\\frac{\\pi(t-T_w)}{T-T_w}\\right)$$"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 实验 1：四种调度曲线 ----------\n",
"def schedule(kind, t, T=2000, Tw=200, peak=1e-3):\n",
"    if kind == 'warmup_cosine':\n",
"        if t < Tw:\n",
"            return peak * t / Tw\n",
"        return peak * 0.5 * (1 + np.cos(np.pi * (t - Tw) / (T - Tw)))\n",
"    if kind == 'step':\n",
"        return peak * 0.1 ** (t // 400)\n",
"    if kind == 'exp':\n",
"        return peak * 0.998 ** t\n",
"    if kind == 'constant':\n",
"        return peak\n",
"\n",
"ts = np.arange(2000)\n",
"fig, ax = plt.subplots(figsize=(8, 4.0))\n",
"for kind, col, lab in [('warmup_cosine', '#4C72B0', 'warmup + cosine'),\n",
"                       ('step', '#55A868', 'step decay (×0.1/400轮)'),\n",
"                       ('exp', '#DD8452', 'exp decay'),\n",
"                       ('constant', '#C44E52', 'constant')]:\n",
"    ax.plot(ts, [schedule(kind, t) for t in ts], label=lab, color=col, lw=1.5)\n",
"ax.set_xlabel('step'); ax.set_ylabel('learning rate')\n",
"ax.set_title('常见学习率调度', fontsize=12)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()"),
code(
"# ---------- 实验 2：不同调度下的收敛对比（简单二次函数 + 噪声） ----------\n",
"rng = np.random.default_rng(1)\n",
"a = 0.1\n",
"f_grad = lambda w: a * w + rng.normal(scale=0.05)\n",
"\n",
"def run(sch, T=2000, Tw=200, peak=0.5):\n",
"    w = 3.0; dists = []\n",
"    for t in range(T):\n",
"        eta = schedule(sch, t, T, Tw, peak)\n",
"        w = w - eta * f_grad(w)\n",
"        dists.append(abs(w))\n",
"    return np.array(dists)\n",
"\n",
"fig, ax = plt.subplots(figsize=(8, 4.0))\n",
"for sch, col, lab in [('warmup_cosine', '#4C72B0', 'warmup+cosine'),\n",
"                      ('step', '#55A868', 'step'),\n",
"                      ('constant', '#C44E52', 'constant')]:\n",
"    ax.plot(run(sch), label=lab, color=col, lw=1.4)\n",
"ax.set_xlabel('step'); ax.set_ylabel('|w|')\n",
"ax.set_title('带噪二次函数：调度帮助后期精细收敛', fontsize=12)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()\n",
"print('constant 后期在噪声下震荡；warmup+cosine 平滑收敛到更小 |w|')"),
md("## §2 梯度裁剪（gradient clipping）\n",
   "\n",
   "**为什么**：RNN / LLM 的梯度范数可能随步长爆炸（连乘效应）→ 更新过大直接毁掉参数。\n",
   "\n",
   "$$g \\gets g \\cdot \\min\\left(1,\\;\\frac{\\text{max\\_norm}}{\\|g\\|_2}\\right)$$\n",
   "\n",
   "只改方向长度、不改方向；`max_norm` 常用 1.0。PyTorch：`torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)`。\n",
   "\n",
   "## §3 梯度累积（gradient accumulation）\n",
   "\n",
   "显存不够跑大 batch 时：小 batch 前向/反向 N 次，**梯度累加后再更新**，等价于 N 倍大 batch（权重更新一次）。\n",
   "\n",
   "注意：BN / 统计量按小 batch 计算会与真大 batch 有差异；LayerNorm 不受影响（逐 token）→ LLM 常用。"),
code(
"# ---------- 实验 3：梯度裁剪救爆炸 ----------\n",
"g_big = np.array([1e4, -3e3, 8e3])\n",
"g_clip = g_big * min(1.0, 1.0 / np.linalg.norm(g_big))\n",
"print(f'裁剪前 ||g||={np.linalg.norm(g_big):.3e} -> 裁剪后 ||g||={np.linalg.norm(g_clip):.3f}, 方向cos={np.dot(g_big,g_clip)/(np.linalg.norm(g_big)*np.linalg.norm(g_clip)):.6f}')\n",
"assert np.isclose(np.linalg.norm(g_clip), 1.0)\n",
"print('方向保持：裁剪只改模长不改方向')"),
code(
"# ---------- 实验 4：梯度累积 vs 大 batch 等价性 ----------\n",
"rng = np.random.default_rng(2)\n",
"N, D = 128, 4\n",
"X = rng.normal(size=(N, D)); w_true = rng.normal(size=D)\n",
"y = X @ w_true + rng.normal(scale=0.1, size=N)\n",
"\n",
"def g_batch(idx):\n",
"    r = X[idx] @ w0 - y[idx]\n",
"    return X[idx].T @ r / len(idx)\n",
"\n",
"w0 = np.zeros(D)\n",
"g_full = g_batch(np.arange(N))            # 128 的全批梯度\n",
"g_acc = np.zeros(D)\n",
"for s in range(4):                        # 4 × 32 累积\n",
"    g_acc += g_batch(np.arange(s * 32, (s + 1) * 32)) / 4\n",
"print(f'全批梯度与累积梯度最大差: {np.abs(g_full - g_acc).max():.2e}')\n",
"assert np.abs(g_full - g_acc).max() < 1e-14\n",
"print('等价性验证通过：4×32 累积 = 1×128 全批（严格平均）')"),
md("## §4 EMA / SWA（参数滑动平均）\n",
   "\n",
   "对**参数**做 EMA：$\\theta_{ema} \\gets \\beta \\theta_{ema} + (1-\\beta)\\theta$，推理用 EMA 参数。\n",
   "\n",
   "作用：权重在多个局部极小间振荡时，EMA 取「质心」→ 更平坦、泛化更好（尤其配合 cosine 退火 = SWA）。\n",
   "\n",
   "## §5 常见 bug 与面试追问\n",
   "\n",
   "- **warmup 步数太短**：大模型至少数百步，否则 loss 早期 spike\n",
   "- **cosine 忘留最小 lr**：降到底会破坏收敛，LLM 常设 `eta_min = peak * 0.1`\n",
   "- **clip 与 lr 顺序**：先 clip 梯度，再优化器更新\n",
   "- **梯度累积后忘除以 N**：累积的是和不是均值，步长被放大 N 倍\n",
   "\n",
   "## §6 自测清单\n",
   "\n",
   "- [ ] 画四种调度曲线（本文已出图）\n",
   "- [ ] 默写 warmup 与 cosine 公式\n",
   "- [ ] 默写梯度裁剪公式并解释方向不变\n",
   "- [ ] 解释梯度累积为什么等价大 batch（严格平均时）\n",
   "- [ ] 说清 EMA 为什么提升泛化\n",
   "\n",
   "> 💡 下节预告：二阶方法（牛顿法/BFGS/K-FAC，06 篇），大模型内存实战（07 篇）。"),
]
}

# =====================================================================
# 06-二阶优化方法
# =====================================================================
nb06 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 🔬 06-二阶优化方法\n",
   "\n",
   "> 目标：牛顿法为什么是「曲率自适应」、为什么深度学习用不起、拟牛顿 BFGS / L-BFGS 与 K-FAC 的思路。\n",
   "\n",
   "## §1 牛顿法\n",
   "\n",
   "对 $f$ 做二阶泰勒展开求极小：$f(w+\\Delta) \\approx f(w) + g^\\top\\Delta + \\tfrac12 \\Delta^\\top H \\Delta$\n",
   "\n",
   "对 $\\Delta$ 求导为零 → $\\boxed{\\Delta = -H^{-1} g}$，更新 $w \\gets w - H^{-1}g$。\n",
   "\n",
   "**与梯度下降的关系**：梯度下降是「以欧氏度量」的最速下降；牛顿法是「以 $H$ 为度量的内积空间」的最速下降 → 对病态条件数（椭圆等高线）天然自适应曲率，**一步到位（二次函数）**。\n",
   "\n",
   "**代价**：$H$ 是 $n\\times n$（$n$=参数量），存 $O(n^2)$、求逆 $O(n^3)$ → 7B 模型 $n^2=4.9\\times10^{19}$，完全不可行。"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 实验 1：病态二次型上 GD vs 牛顿法 ----------\n",
"def quad_grad(w, H):\n",
"    return H @ w\n",
"\n",
"H = np.diag([1.0, 100.0])   # 条件数 100：y 方向陡\n",
"w0 = np.array([1.0, 1.0])\n",
"\n",
"def run_gd(steps=400, lr=0.01):\n",
"    w = w0.copy(); dists = [np.linalg.norm(w)]\n",
"    for _ in range(steps):\n",
"        w = w - lr * quad_grad(w, H)\n",
"        dists.append(np.linalg.norm(w))\n",
"    return np.array(dists)\n",
"\n",
"def run_newton():\n",
"    w = w0.copy(); dists = [np.linalg.norm(w)]\n",
"    for _ in range(20):\n",
"        w = w - np.linalg.solve(H, quad_grad(w, H))   # H 恒定\n",
"        dists.append(np.linalg.norm(w))\n",
"    return np.array(dists)\n",
"\n",
"fig, ax = plt.subplots(figsize=(8, 4.0))\n",
"ax.plot(run_gd(), label='GD lr=0.01', color='#C44E52', lw=1.5)\n",
"ax.plot(run_newton(), label='牛顿法（20 步内归零）', color='#4C72B0', lw=1.5, marker='o', ms=4)\n",
"ax.set_xlabel('step'); ax.set_ylabel('||w||')\n",
"ax.set_title('条件数=100 的二次型：GD 震荡爬行，牛顿法一步到最优', fontsize=12)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()\n",
"print('GD 400 步后 ||w||=%.3f；牛顿法第 1 步即归零' % run_gd()[-1])"),
md("## §2 为什么深度学习不用牛顿法\n",
   "\n",
   "1. **存不下**：$H \\in \\mathbb{R}^{n\\times n}$，$O(n^2)$ 内存（7B 模型不可行）\n",
   "2. **算不起**：求逆 $O(n^3)$\n",
   "3. **非凸**：$H$ 未必正定，$H^{-1}g$ 可能不是下降方向（需 damping）\n",
   "4. **mini-batch 噪声**：Hessian 估计方差大\n",
   "\n",
   "缓解：**拟牛顿**——用梯度差近似 $H^{-1}$。\n",
   "\n",
   "## §3 BFGS 与 L-BFGS\n",
   "\n",
   "- **BFGS**：维护 $B_k \\approx H_k$，用两次迭代的梯度差 $s_k, y_k$ 做秩 2 更新（曲率条件 $s_k^\\top y_k > 0$），无需二阶导\n",
   "- **L-BFGS**：不存 $B_k$，只存最近 $m$ 步的 $(s_k, y_k)$，用两循环递归近似 $H^{-1}$ → 内存 $O(mn)$\n",
   "- 适用：中小规模凸问题（逻辑回归、SVM 对偶）效果好；深度网络仍不用（非凸 + 大数据）\n",
   "\n",
   "## §4 K-FAC / Shampoo 一句话直觉\n",
   "\n",
   "- **K-FAC**：把 Fisher 矩阵按层块对角化，每块近似为激活与梯度的 Kronecker 积 $A \\otimes G$，求逆用 $A^{-1}\\otimes G^{-1}$（小矩阵求逆）→ 二阶信息近似，仍是 $O(n)$ 内存\n",
   "- **Shampoo**：每层用 Kronecker 因子近似 AdaGrad 累积矩阵\n",
   "\n",
   "## §5 面试追问与自测\n",
   "\n",
   "- 牛顿法更新公式：$w \\gets w - H^{-1}g$；为什么二次函数一步到位\n",
   "- 条件数如何影响 GD / 牛顿法的步数（本文实验）\n",
   "- BFGS 的曲率条件 $s^\\top y > 0$ 含义\n",
   "- K-FAC 的「块对角 + Kronecker」为什么省内存\n",
   "\n",
   "> 💡 下节预告：FP16/BF16 混合精度与 Adam 内存分析（07 篇）。"),
]
}

# =====================================================================
# 07-大模型训练优化实践
# =====================================================================
nb07 = {
    "nbformat": 4, "nbformat_minor": 5, "metadata": META, "cells": [
md("# 🏗️ 07-大模型训练优化实践\n",
   "\n",
   "> 目标：把前面所有优化知识接到**LLM 训练**——FP16/BF16 混合精度、Adam 优化器状态内存、ZeRO 分片。\n",
   "\n",
   "## §1 三种浮点格式\n",
   "\n",
   "| 格式 | 总位 | 指数位 | 尾数位 | 最大有限值 | 最小正常值 | 相对精度 |\n",
   "|------|------|--------|--------|------------|------------|----------|\n",
   "| FP32 | 32 | 8 | 23 | $\\approx 3.4\\times10^{38}$ | $1.2\\times10^{-38}$ | $\\sim10^{-7}$ |\n",
   "| FP16 | 16 | 5 | 10 | 65504 | $6.1\\times10^{-5}$ | $\\sim10^{-3}$ |\n",
   "| BF16 | 16 | 8 | 7 | $\\approx 3.4\\times10^{38}$ | $1.2\\times10^{-38}$ | $\\sim10^{-2}$ |\n",
   "\n",
   "**BF16 = FP32 的指数范围 + 更少的尾数**：梯度/激活很少溢出（LLM 主流）；FP16 范围窄，需要 **loss scaling**。"),
code(
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"\n",
"plt.rcParams['font.sans-serif'] = ['Microsoft YaHei', 'SimHei', 'DejaVu Sans']\n",
"plt.rcParams['axes.unicode_minus'] = False\n",
"\n",
"# ---------- 实验 1：FP16 溢出 vs BF16 不溢出 ----------\n",
"vals = np.array([1e-4, 1e-3, 0.01, 1.0, 100.0, 5e4])\n",
"fp16 = vals.astype(np.float16)\n",
"bf16 = vals.astype(np.bfloat16)\n",
"fp32 = vals.astype(np.float32)\n",
"print('数值       FP32        FP16        BF16')\n",
"for v, a, b, c in zip(vals, fp32, fp16, bf16):\n",
"    print(f'{v:8.1e}  {a:12.4e}  {b:12.4e}  {c:12.4e}')\n",
"print()\n",
"print('FP16 最大有限值:', np.finfo(np.float16).max)\n",
"print('BF16 最大有限值:', np.finfo(np.bfloat16).max)\n",
"print('结论: 5e4 在 FP16 中已是 inf；BF16 与 FP32 范围一致')"),
code(
"# ---------- 实验 2：loss scaling 救 FP16 ----------\n",
"tiny_grad = 1e-5\n",
"fp16_no_scale = np.float16(tiny_grad)           # 直接存\n",
"scale = np.float16(1024.0)\n",
"fp16_scaled = np.float16(tiny_grad * scale)     # 放大后存\n",
"back = np.float32(fp16_scaled) / np.float32(scale)  # 反缩放\n",
"print(f'原始梯度={tiny_grad:.1e}')\n",
"print(f'FP16 直接存={float(fp16_no_scale):.3e}（下溢→0）')\n",
"print(f'FP16 缩放存储后反缩放={back:.3e}（保住了）')\n",
"assert float(fp16_no_scale) == 0.0 and back > 0\n",
"print('loss scaling 原理演示通过')"),
md("## §2 混合精度训练流程\n",
   "\n",
   "1. 参数 FP32 master copy 一份\n",
   "2. 前向/反向在 FP16/BF16 上做（省显存、加速）\n",
   "3. 梯度反缩放（FP16）或直接（BF16）后转 FP32\n",
   "4. 优化器状态与更新在 FP32 master 上做（累加精度）\n",
   "\n",
   "**为什么 optimizer 状态要 FP32**：Adam 的 $m,v$ 累加必须高精度，否则小更新丢失。"),
code(
"# ---------- 实验 3：Adam 优化器状态内存分析 ----------\n",
"# 参数量 -> 显存（FP32 每个参数：参数4B + m 4B + v 4B = 12B；BF16 参数/梯度可省）\n",
"params = np.array([0.5, 1, 3, 7, 13, 70, 175])  # 十亿参数\n",
"bytes_per_p = 12  # 参数4 + m4 + v4（FP32 优化器状态）\n",
"mem_fp32 = params * bytes_per_p * 1e9 / 1e9     # GB\n",
"\n",
"fig, ax = plt.subplots(figsize=(8, 4.0))\n",
"ax.plot(params, mem_fp32, 'o-', color='#4C72B0', lw=1.6, label='Adam FP32 优化器状态+参数 (12B/参数)')\n",
"ax.plot(params, params * 8, 's--', color='#55A868', lw=1.4, label='BF16 训练近似 (8B/参数)')\n",
"for p, m in zip(params, mem_fp32):\n",
"    ax.annotate(f'{m:.0f}GB', (p, m), textcoords='offset points', xytext=(6, 4), fontsize=8)\n",
"ax.set_xlabel('参数量 (B)'); ax.set_ylabel('显存 (GB)')\n",
"ax.set_title('7B 模型 Adam 优化器状态 ≈ 84GB（远超单卡）', fontsize=12)\n",
"ax.grid(alpha=0.3); ax.legend(fontsize=9)\n",
"plt.tight_layout(); plt.show()\n",
"print('口算：7B × 12B = 84GB 优化器状态+参数（不含激活/梯度）')"),
code(
"# ---------- 实验 4：ZeRO 分片内存曲线 ----------\n",
"# ZeRO-1/2/3：分别把 优化器状态 / +梯度 / +参数 分片到 N 卡\n",
"N = np.arange(1, 65)\n",
"B = 7e9 * 12 / 1e9   # 7B FP32 全量 GB\n",
"def zero_mem(stage, n):\n",
    "    base = B  # 全量（未分片）\n",
    "    if stage == 1:  # 只分优化器状态(8B/p)，参数+梯度(4B/p) 每卡都有\n",
    "        return 7 * 8 / n + 7 * 4\n",
    "    if stage == 2:  # 优化器状态+梯度(10B/p) 分片\n",
    "        return 7 * 10 / n + 7 * 2\n",
    "    if stage == 3:  # 全部(12B/p) 分片\n",
    "        return 7 * 12 / n\n",
    "    return base\n",
"\n",
"fig, ax = plt.subplots(figsize=(8, 4.0))\n",
"for st, col, lab in [(0, '#C44E52', 'Baseline (不分片)'),\n",
"                     (1, '#DD8452', 'ZeRO-1: 优化器状态分片'),\n",
"                     (2, '#55A868', 'ZeRO-2: +梯度分片'),\n",
"                     (3, '#4C72B0', 'ZeRO-3: +参数分片')]:\n",
"    if st == 0:\n",
"        ax.plot(N, np.full_like(N, B), color=col, lw=1.5, label=lab)\n",
"    else:\n",
"        ax.plot(N, [zero_mem(st, n) for n in N], color=col, lw=1.5, label=lab)\n",
"ax.set_xlabel('GPU 数量'); ax.set_ylabel('每卡显存 (GB)')\n",
"ax.set_title('7B 模型 ZeRO 分片：越到后期省得越多', fontsize=12)\n",
"ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
"plt.tight_layout(); plt.show()\n",
"print('8 卡 ZeRO-3: %.1fGB/卡 vs Baseline %.1fGB' % (zero_mem(3, 8), B))"),
md("## §3 显存换时间的组合拳\n",
   "\n",
   "- **梯度累积**：等效大 batch，显存不变（见 05 篇）\n",
   "- **激活重计算（gradient checkpointing）**：不存中间激活，反向时重算 → 显存 $O(L)$ 变 $O(\\sqrt L)$ 量级，代价约 30% 时间\n",
   "- **ZeRO-offload**：优化器状态 / 梯度挪到 CPU，GPU 显存进一步降\n",
   "- **流水并行 + 张量并行**：模型切分，配 ZeRO 组成三维并行\n",
   "\n",
   "## §4 面试速答\n",
   "\n",
   "- **为什么 BF16 不是 FP16**：指数位 8=FP32，范围不溢出 → 免 loss scaling；尾数少但训练可容忍\n",
   "- **7B Adam 状态口算**：$7\\times10^9\\times 12$B $= 84$GB\n",
   "- **ZeRO 三阶段**：优化器状态 / +梯度 / +参数 依次分片，通信量递增\n",
   "- **为什么优化器状态必须 FP32**：Adam 累加精度\n",
   "\n",
   "## §5 自测清单\n",
   "\n",
   "- [ ] 默写 FP16/BF16 指数位与最大范围\n",
   "- [ ] 演示 loss scaling（本文实验）\n",
   "- [ ] 口算 7B Adam 状态显存（84GB）\n",
   "- [ ] 画出 ZeRO-1/2/3 内存曲线（本文已出图）\n",
   "- [ ] 说清重计算/offload 换什么、花什么\n",
   "\n",
   "> 💡 本笔记验收：`08-优化算法/README.md` 验收清单「混合精度 / ZeRO 内存计算」打勾。"),
]
}

for fn, nb in [('05-学习率调度与训练策略.ipynb', nb05),
               ('06-二阶优化方法.ipynb', nb06),
               ('07-大模型训练优化实践.ipynb', nb07)]:
    with open(os.path.join(OUT, fn), 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    print('created', fn)
